repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: "./.venv/Scripts/pylint.exe"
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the source
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]
